#!/bin/bash

# Place this file in .git/hooks to have it take affect in any git repository

# This way you can customize which branches should be skipped when
# prepending commit message.
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
# This regex removes all non-numeric characters, so if there are
# other numbers in your branch, they WILL be added to the issue number
ISSUE=$(echo $BRANCH_NAME | sed 's/[^0-9]*//g')

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e '$a\'$'\n'$ISSUE $1
fi
